### PR TITLE
Upgraded the issue templates

### PR DESCRIPTION
**Pull request by Ln11211**
I have ugraded our issue templates for reporting a bug, doccumenting an issue and to request a feature. I have also tested them all by creating a issue each. They are working fine..

issue template

### CODE REVIEW

**Comment by lohanidamodar** [comment]
@Ln11211  Great work. One more change before we can approve. We have made few changes in the language and also the format of Code of conduct. Please check https://github.com/appwrite/appwrite template and update accordingly.
Thank you.

**Comment by Ln11211** [comment]
@lohanidamodar , will do, thank you 😊

**Comment by Ln11211** [comment]
@lohanidamodar , so in the branch naming convention  " TYPE-ISSUE_ID-DESCRIPTION" , the type in this case will be DOC right ?

**Comment by Ln11211** [comment]
@lohanidamodar , I tried changing the main branch name and it doesn't seem to change it in the pr, can you please help me out ?  I named it as feat-#5-Add_Issues_Templates, so should I create a new branch and restart again ?

**Comment by Ln11211** [comment]
@lohanidamodar, I think I have to create a new pull request..

**Comment by lohanidamodar** [comment]
@Ln11211 I am not sure what mean. This is good. You don't need another PR just update the templates with the fixes and push it in your main branch. That's ok.

**Comment by Ln11211** [comment]
@lohanidamodar , I'm sorry but what exactly should I update in my templates ?, did I miss anything?

**Comment by Ln11211** [comment]
@lohanidamodar  so I have noticed that the templates were updated with "Code of conduct " and I have done the same. Please review...

**Comment by Ln11211** [comment]
@lohanidamodar , well, I also noticed that the original appwrite has a "[workflows](https://github.com/appwrite/appwrite/tree/master/.github/workflows)" folder in ".github" folder and it contains two .yml files, should I also add them  ?

**Review by lohanidamodar — APPROVED** [review]
@Ln11211 Great work 🚀 No need to add workflows. Please feel free to look for more PRs you might be interested in helping with on our long list of [Hacktoberfest friendly issues](https://github.com/search?q=org%3Aappwrite+org%3Autopia-php+is%3Aissue+label%3Ahacktoberfest+created%3A%3E2021-01-01+is%3Aopen&type=issues) to help make Appwrite better.

**Comment by christyjacob4** [comment]
THANK YOU! All changes merged 🥳

Please reach out to me on our [Discord server](https://appwrite.io/discord) if you would like to claim your Appwrite swags! As a way of saying thank you, we would also love to invite you to join the Appwrite organization on GitHub. Please share your GitHub username with us on Discord.  

You can accept the invite by visiting https://github.com/orgs/appwrite/invitation. By joining our team, you will officially be an Appwrite maintainer on GitHub.

You can change your membership [visibility settings](https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/publicizing-or-hiding-organization-membership), so your new Appwrite team membership badge will show up on your personal GitHub profile.

Please feel free to look for more PRs you might be interested in helping with on our long list of [Hacktoberfest friendly issues](https://github.com/search?q=org%3Aappwrite+org%3Autopia-php+is%3Aissue+label%3Ahacktoberfest+created%3A%3E2021-01-01+is%3Aopen&type=issues) and help make Appwrite better :)

**Pull request merged**
